export enum actionTypes{
    "USER_DATA"="USER_DATA",
    "DELETE_USER"="DELETE_USER",
    "ADD_NEW_USER"="ADD_NEW_USER",
    "ADD_WEATHER_DATA"="ADD_WEATHER_DATA",
    "WEATHER_DATA"="WEATHER_DATA",
    "GET_WEATHER_DATA"="GET_WEATHER_DATA",
    "ASYNC_CHANGE_CITY"="ASYNC_CHANGE_CITY",
    "CHANGE_CITY"="CHANGE_CITY",
    "CHANGE_LOADING_STATUS"="CHANGE_LOADING_STATUS",
    "CHANGE_SELECTED_CARD_NO"="CHANGE_SELECTED_CARD_NO",
    "RECENT_API_CALLS"="RECENT_API_CALLS"
}