export enum actionTypes{
    "USER_DATA"="USER_DATA",
    "DELETE_USER"="DELETE_USER",
    "ADD_NEW_USER"="ADD_NEW_USER",
    "ADD_WEATHER_DATA"="ADD_WEATHER_DATA",
    "WEATHER_DATA"="WEATHER_DATA",
    "GET_WEATHER_DATA"="GET_WEATHER_DATA",
    "CHANGE_CITY"="CHANGE_CITY",
    "GET_CITY"="GET_CITY",
    "CHANGE_LOADING_STATUS"="CHANGE_LOADING_STATUS",
}